import type { Effect, ExitId, GameState, RoomType, Stat } from '../types';

// Room and objective actions that follow the standard pattern: a die, an
// optional stat, three outcomes. Movement, searching, hiding, fighting and
// items are handled in the engine because they need targets.

export interface Outcome {
  /** Short, shown on the button before you commit. */
  sum: string;
  /** Written to the log afterwards. */
  text: string;
  effect?: Effect;
}

export interface RoomActionDef {
  id: string;
  rooms: RoomType[];
  group: 'room' | 'goal';
  label: string;
  desc: string;
  icon: string;
  /** No stat: any die does the same thing. */
  stat?: Stat;
  mod?: number;
  noise: number;
  /** Uses per room. */
  limit?: number;
  /** Counts as a flight check for the Pilot. */
  flight?: boolean;
  step?: { exit: ExitId; step: number };
  /** Progress needed: a clean result adds 2, a cost adds 1. */
  work?: number;
  /** Item used up when the step completes. */
  consumes?: 'fuelcell';
  when?: (s: GameState) => boolean;
  clean: Outcome;
  cost?: Outcome;
  fail?: Outcome;
}

const hasItem = (s: GameState, id: string) => s.player.items.some((i) => i.id === id);
const hasPersonal = (s: GameState, id: string) => s.scenario.personal === id && !s.progress.personalDone;
const creatureHere = (s: GameState) => s.creatures.some((c) => c.room === s.player.room);

export const ROOM_ACTIONS: RoomActionDef[] = [
  // ── medbay ──
  {
    id: 'treat',
    rooms: ['medbay'],
    group: 'room',
    label: 'Treat your wounds',
    desc: 'Stitch, spray and bandage.',
    icon: 'heal',
    stat: 'tech',
    noise: 0,
    limit: 3,
    clean: { sum: 'Heal 2', text: 'You clean and close the worst of it. The auto-doc does the rest.', effect: { heal: 2 } },
    cost: { sum: 'Heal 1, +1 stress', text: 'You patch yourself up, badly, biting down on a strap.', effect: { heal: 1, stress: 1 } },
    fail: { sum: 'Nothing, and noise', text: 'A tray of instruments hits the floor with a crash.', effect: { noise: 2 } },
  },
  {
    id: 'scan',
    rooms: ['medbay'],
    group: 'room',
    label: 'Run a body scan',
    desc: 'Checks you — and anyone with you — for infection. And for a heartbeat.',
    icon: 'scan',
    noise: 1,
    limit: 2,
    clean: { sum: 'Scan', text: 'The scanner arm sweeps over you with a soft chime.', effect: { scan: true } },
  },
  {
    id: 'purge',
    rooms: ['medbay', 'lab'],
    group: 'room',
    label: 'Purge the infection',
    desc: 'A brutal antiviral flush. It hurts.',
    icon: 'heal',
    stat: 'tech',
    mod: -1,
    noise: 1,
    when: (s) => s.player.infected && s.player.infectionKnown,
    clean: { sum: 'Cured', text: 'The flush burns like acid in your veins, and then it’s clean.', effect: { cure: true } },
    cost: { sum: 'Cured, 1 damage', text: 'It works. It also nearly kills you.', effect: { cure: true, hp: -1 } },
    fail: { sum: '1 damage, still infected', text: 'You convulse on the table. When it stops, you are still not alone in your body.', effect: { hp: -1 } },
  },
  // ── galley ──
  {
    id: 'eat',
    rooms: ['galley'],
    group: 'room',
    label: 'Eat something',
    desc: 'Sit down. Eat. Pretend.',
    icon: 'calm',
    stat: 'nerve',
    noise: 0,
    limit: 2,
    clean: { sum: '−2 stress, heal 1', text: 'Reconstituted stew, eaten cold from the tin. You feel almost human.', effect: { stress: -2, heal: 1 } },
    cost: { sum: '−1 stress', text: 'You get some of it down.', effect: { stress: -1 } },
    fail: { sum: 'Noise', text: 'You knock a stack of trays off the counter. The clatter goes on forever.', effect: { noise: 2 } },
  },
  // ── quarters ──
  {
    id: 'rest',
    rooms: ['quarters'],
    group: 'room',
    label: 'Rest in a bunk',
    desc: 'Close your eyes. Just for a minute.',
    icon: 'calm',
    stat: 'nerve',
    noise: 0,
    limit: 2,
    clean: { sum: 'Heal 1, −2 stress', text: 'You sleep for twenty minutes, and it is the best sleep of your life.', effect: { heal: 1, stress: -2 } },
    cost: { sum: '−1 stress', text: 'You don’t sleep, but you lie still, and that helps.', effect: { stress: -1 } },
    fail: { sum: 'Nightmare: +1 stress', text: 'You dream of the pods opening, one by one, and wake with a shout.', effect: { stress: 1, noise: 1 } },
  },
  // ── reactor ──
  {
    id: 'stabilise',
    rooms: ['reactor'],
    group: 'room',
    label: 'Stabilise the reactor',
    desc: 'Buy the ship some time.',
    icon: 'clock',
    stat: 'tech',
    noise: 1,
    limit: 1,
    clean: { sum: '+3 rounds', text: 'You coax the containment field back into line. The countdown steadies.', effect: { clock: 3 } },
    cost: { sum: '+2 rounds, 1 damage', text: 'You manage it, but the radiation alarm was screaming the whole time.', effect: { clock: 2, hp: -1 } },
    fail: { sum: '1 damage', text: 'A coolant line spits scalding vapour across your arm.', effect: { hp: -1, noise: 1 } },
  },
  {
    id: 'overload',
    rooms: ['reactor'],
    group: 'goal',
    label: 'Arm the reactor overload',
    desc: 'With the command codes. The ship will burn in 6 rounds, and everything on it.',
    icon: 'fire',
    noise: 2,
    when: (s) => hasItem(s, 'codes') && !s.progress.selfDestruct,
    clean: { sum: 'Ship burns in 6', text: 'You slot the codes and turn the key. Every alarm on the ship starts at once. Now run.', effect: { selfDestruct: true } },
  },
  // ── bridge ──
  {
    id: 'plans',
    rooms: ['bridge'],
    group: 'room',
    label: 'Pull up the deck plans',
    desc: 'Name every room on the map.',
    icon: 'map',
    stat: 'tech',
    noise: 0,
    limit: 1,
    when: (s) => !s.progress.mapRevealed,
    clean: { sum: 'Reveal the map', text: 'The whole ship blooms on the screen, every room labelled.', effect: { revealMap: true } },
    cost: { sum: 'Reveal the map, noise', text: 'The plans come up — with an alarm chirp you can’t silence.', effect: { revealMap: true, noise: 2 } },
    fail: { sum: 'Noise', text: 'ACCESS DENIED, the console announces, loudly.', effect: { noise: 1 } },
  },
  {
    id: 'bridge-codes',
    rooms: ['bridge'],
    group: 'room',
    label: 'Crack the command codes',
    desc: 'The captain’s authority. It opens a lot of doors.',
    icon: 'key',
    stat: 'tech',
    mod: -1,
    noise: 1,
    limit: 2,
    when: (s) => !hasItem(s, 'codes'),
    clean: { sum: 'Get the codes', text: 'The console blinks COMMAND AUTHORITY TRANSFERRED. The chip slides out warm.', effect: { item: 'codes' } },
    cost: { sum: 'Codes, loud alarm', text: 'You get the codes. The intrusion alarm goes off anyway.', effect: { item: 'codes', noise: 2 } },
    fail: { sum: 'Lockout alarm', text: 'Three wrong tries. A lockout siren wails through the ship.', effect: { noise: 2 } },
  },
  {
    id: 'blackbox',
    rooms: ['bridge'],
    group: 'goal',
    label: 'Pull the flight recorder',
    desc: 'Your secret objective. It’s bolted in.',
    icon: 'box',
    stat: 'might',
    noise: 2,
    when: (s) => hasPersonal(s, 'blackbox') && !hasItem(s, 'blackbox'),
    clean: { sum: 'Get the recorder', text: 'The bolts give and the orange box comes free in your hands.', effect: { item: 'blackbox' } },
    cost: { sum: 'Recorder, 1 damage', text: 'It comes free all at once and takes skin off your knuckles.', effect: { item: 'blackbox', hp: -1 } },
    fail: { sum: 'Noise', text: 'Your wrench slips and bangs off the console.', effect: { noise: 1 } },
  },
  // ── comms ──
  {
    id: 'listen',
    rooms: ['comms'],
    group: 'room',
    label: 'Listen on the internal channels',
    desc: 'Every open mic on the ship. See where things are moving.',
    icon: 'eye',
    stat: 'wits',
    noise: 0,
    limit: 2,
    clean: { sum: 'See everything, 2 rounds', text: 'You patch into every intercom. You can hear them all moving.', effect: { cameras: 2 } },
    cost: { sum: 'See everything, 1 round', text: 'You catch a few seconds of it before the feedback starts.', effect: { cameras: 1, noise: 1 } },
    fail: { sum: 'Feedback screech', text: 'A howl of feedback through every speaker aboard.', effect: { noise: 2 } },
  },
  // ── lab ──
  {
    id: 'analyse',
    rooms: ['lab'],
    group: 'room',
    label: 'Study the samples',
    desc: 'Work out what happened here.',
    icon: 'log',
    stat: 'tech',
    noise: 0,
    limit: 1,
    when: (s) => !s.progress.truth,
    clean: { sum: 'Find a log', text: 'The sample records fill in part of the story.', effect: { clue: true } },
    cost: { sum: 'Find a log, +1 stress', text: 'You find what you were looking for. You look at the jars too long.', effect: { clue: true, stress: 1 } },
    fail: { sum: '+1 stress', text: 'Something in a jar moves when you tap the glass.', effect: { stress: 1 } },
  },
  {
    id: 'wipe',
    rooms: ['lab'],
    group: 'goal',
    label: 'Wipe the research records',
    desc: 'Your secret objective.',
    icon: 'log',
    stat: 'tech',
    noise: 1,
    when: (s) => hasPersonal(s, 'wipe'),
    clean: { sum: 'Records gone', text: 'DELETE ALL? Yes. Your name goes with everything else.', effect: { wipe: true } },
    cost: { sum: 'Records gone, noise', text: 'It takes a hammer to the backup drive, in the end.', effect: { wipe: true, noise: 2 } },
    fail: { sum: 'Noise', text: 'The terminal refuses you and beeps about it.', effect: { noise: 1 } },
  },
  // ── hydroponics ──
  {
    id: 'forage',
    rooms: ['hydroponics'],
    group: 'room',
    label: 'Pick something to eat',
    desc: 'Fresh food. Real food.',
    icon: 'calm',
    stat: 'wits',
    noise: 0,
    limit: 1,
    clean: { sum: 'Heal 1, −1 stress', text: 'A handful of strawberries, warm from the lamps.', effect: { heal: 1, stress: -1 } },
    cost: { sum: '−1 stress', text: 'Some bitter leaves. Better than nothing.', effect: { stress: -1 } },
    fail: { sum: '+1 stress', text: 'Something in the leaves was not a leaf.', effect: { stress: 1 } },
  },
  // ── security ──
  {
    id: 'cameras',
    rooms: ['security'],
    group: 'room',
    label: 'Work the camera feeds',
    desc: 'See every creature aboard for a while.',
    icon: 'eye',
    stat: 'tech',
    noise: 0,
    limit: 2,
    clean: { sum: 'See everything, 4 rounds', text: 'You get the feeds up and patched to your wrist unit.', effect: { cameras: 4 } },
    cost: { sum: 'See everything, 2 rounds', text: 'Half the cameras come up.', effect: { cameras: 2 } },
    fail: { sum: 'Noise', text: 'The console shorts with a bang.', effect: { noise: 1 } },
  },
  // ── observation ──
  {
    id: 'gaze',
    rooms: ['observation'],
    group: 'room',
    label: 'Look at the stars',
    desc: 'Remember that there is a universe outside this ship.',
    icon: 'calm',
    stat: 'nerve',
    noise: 0,
    limit: 1,
    clean: { sum: '−3 stress', text: 'You breathe. The stars don’t care about any of this, and somehow that helps.', effect: { stress: -3 } },
    cost: { sum: '−2 stress', text: 'It helps, for a while.', effect: { stress: -2 } },
    fail: { sum: '−1 stress', text: 'Your reflection in the glass keeps pulling your eye.', effect: { stress: -1 } },
  },
  // ── airlock ──
  {
    id: 'blow',
    rooms: ['airlock'],
    group: 'room',
    label: 'Blow the airlock',
    desc: 'Grab the handhold and open the outer door. Anything in here that isn’t holding on goes into space.',
    icon: 'breach',
    stat: 'might',
    noise: 1,
    when: (s) => creatureHere(s) && !s.rooms[s.player.room]!.spent,
    clean: { sum: 'Space everything here', text: 'You haul the red handle. The air goes out in one roar, and everything with it. You hold on.', effect: { killHere: true } },
    cost: { sum: 'Space it, 1 damage, lose an item', text: 'It goes. You nearly go with it, and something tears out of your grip.', effect: { killHere: true, hp: -1, loseItem: 'random' } },
    fail: { sum: 'Space it, 2 damage', text: 'It goes. Your arm nearly comes out of its socket holding on.', effect: { killHere: true, hp: -2 } },
  },
  // ── captain ──
  {
    id: 'safe',
    rooms: ['captain'],
    group: 'room',
    label: 'Crack the wall safe',
    desc: 'The captain kept something important in here.',
    icon: 'key',
    stat: 'tech',
    mod: -1,
    noise: 1,
    limit: 2,
    when: (s) => !hasItem(s, 'codes') && !s.rooms[s.player.room]!.spent,
    clean: { sum: 'Codes and a pistol', text: 'The dial clicks home. Inside: the command chip, and a pistol.', effect: { item: 'codes', flag: 'safe-pistol' } },
    cost: { sum: 'Codes, noise', text: 'You drill it. Loudly. The command chip is inside.', effect: { item: 'codes', noise: 2 } },
    fail: { sum: 'Alarm', text: 'The safe alarm is old, and very loud.', effect: { noise: 2 } },
  },
  // ── cryo ──
  {
    id: 'pods',
    rooms: ['cryo'],
    group: 'room',
    label: 'Check the other pods',
    desc: 'Someone might have left something behind.',
    icon: 'search',
    stat: 'wits',
    noise: 0,
    limit: 1,
    clean: { sum: 'Find a stim', text: 'In the drawer under pod 4: a stim injector, still sealed.', effect: { item: 'stim' } },
    cost: { sum: 'Stim, +1 stress', text: 'A stim — and, in pod 6, what’s left of its owner.', effect: { item: 'stim', stress: 1 } },
    fail: { sum: '+2 stress', text: 'Pod 7 isn’t empty. You wish it were.', effect: { stress: 2 } },
  },
  // ── nest ──
  {
    id: 'nest',
    rooms: ['nest'],
    group: 'room',
    label: 'Destroy the nest',
    desc: 'Nothing more gets born. Much easier with fire.',
    icon: 'fire',
    stat: 'might',
    noise: 3,
    when: (s) => !s.progress.nestDestroyed,
    clean: { sum: 'Destroy it', text: '', effect: { destroyNest: true } },
    cost: { sum: 'Destroy it, 1 damage', text: '', effect: { destroyNest: true, hp: -1 } },
    fail: { sum: '1 damage', text: 'It fights back. The walls fight back.', effect: { hp: -1 } },
  },
  {
    id: 'sample',
    rooms: ['nest'],
    group: 'goal',
    label: 'Cut a tissue sample',
    desc: 'Your secret objective. It will not like this.',
    icon: 'sample',
    stat: 'might',
    noise: 2,
    when: (s) => hasPersonal(s, 'sample') && !hasItem(s, 'sample'),
    clean: { sum: 'Get the sample', text: 'You slice it free and seal the jar. The jar is warm.', effect: { item: 'sample' } },
    cost: { sum: 'Sample, 1 damage', text: 'It lashes you as you cut, but you get it.', effect: { item: 'sample', hp: -1 } },
    fail: { sum: '1 damage', text: 'It lashes out before you get the blade in.', effect: { hp: -1 } },
  },

  // ── exits ──
  {
    id: 'pods-0',
    work: 2,
    rooms: ['engineering'],
    group: 'goal',
    step: { exit: 'pods', step: 0 },
    label: 'Restore power to the pod bay',
    desc: 'Reroute the bus. Escape pod, step 1.',
    icon: 'power',
    stat: 'tech',
    noise: 1,
    clean: { sum: 'Done', text: 'You throw the breaker. Across the ship, the pod bay lights up.' },
    cost: { sum: 'Done, noise', text: 'It takes a few kicks to the junction box.', effect: { noise: 2 } },
    fail: { sum: '1 damage', text: 'The bus arcs. You smell your own hair burning.', effect: { hp: -1 } },
  },
  {
    id: 'pods-1',
    work: 2,
    rooms: ['bridge'],
    group: 'goal',
    step: { exit: 'pods', step: 1 },
    flight: true,
    label: 'Authorise the pod launch',
    desc: 'Escape pod, step 2. Certain with the command codes.',
    icon: 'key',
    stat: 'tech',
    noise: 0,
    clean: { sum: 'Done', text: 'LAUNCH AUTHORISED, says the console, in the captain’s voice.' },
    cost: { sum: 'Done, +1 stress', text: 'You forge it. It takes three tries and all your nerve.', effect: { stress: 1 } },
    fail: { sum: 'Noise', text: 'AUTHORISATION REJECTED, it announces, to the whole ship.', effect: { noise: 1 } },
  },
  {
    id: 'pods-2',
    rooms: ['podbay'],
    group: 'goal',
    step: { exit: 'pods', step: 2 },
    label: 'Launch the escape pod',
    desc: 'Climb in and pull the handle. This ends the run.',
    icon: 'launch',
    noise: 0,
    clean: { sum: 'Escape', text: 'The hatch seals. You pull the handle.', effect: { win: 'pods' } },
  },
  {
    id: 'shuttle-1',
    work: 2,
    consumes: 'fuelcell',
    rooms: ['hangar'],
    group: 'goal',
    step: { exit: 'shuttle', step: 1 },
    label: 'Fuel and prep the shuttle',
    desc: 'Seat the fuel cell and run the pre-flight. Shuttle, step 2.',
    icon: 'power',
    stat: 'tech',
    noise: 1,
    when: (s) => hasItem(s, 'fuelcell'),
    clean: { sum: 'Done', text: 'The cell seats with a clunk. Every light on the shuttle board goes green.', },
    cost: { sum: 'Done, noise', text: 'The pre-flight runs, with every alarm test at full volume.', effect: { noise: 2 } },
    fail: { sum: 'Noise', text: 'The cell won’t seat. You hammer it. It still won’t seat.', effect: { noise: 1 } },
  },
  {
    id: 'shuttle-2',
    rooms: ['hangar'],
    group: 'goal',
    step: { exit: 'shuttle', step: 2 },
    flight: true,
    label: 'Fly it out',
    desc: 'Blow the bay doors and go. This ends the run.',
    icon: 'launch',
    stat: 'wits',
    noise: 3,
    clean: { sum: 'Escape', text: 'The bay doors grind open on the stars. You throttle up.', effect: { win: 'shuttle' } },
    cost: { sum: 'Escape, 1 damage', text: 'You clip the bay door on the way out. You don’t care.', effect: { win: 'shuttle', hp: -1 } },
    fail: { sum: 'Clamps jam, loud', text: 'The docking clamps won’t release. The whole hangar hears you trying.', effect: { noise: 2 } },
  },
  {
    id: 'beacon-0',
    work: 2,
    rooms: ['comms'],
    group: 'goal',
    step: { exit: 'beacon', step: 0 },
    label: 'Realign the array',
    desc: 'Distress call, step 1.',
    icon: 'signal',
    stat: 'tech',
    noise: 1,
    clean: { sum: 'Done', text: 'The dish swings round. A carrier tone. Somebody is out there.' },
    cost: { sum: 'Done, noise', text: 'The dish motor shrieks the whole way round.', effect: { noise: 2 } },
    fail: { sum: 'Noise', text: 'The motor grinds and stalls.', effect: { noise: 1 } },
  },
  {
    id: 'beacon-1',
    rooms: ['comms'],
    group: 'goal',
    step: { exit: 'beacon', step: 1 },
    label: 'Broadcast the distress call',
    desc: 'Help arrives at the Airlock in 6 rounds. Very loud.',
    icon: 'signal',
    noise: 3,
    clean: { sum: 'Help in 6 rounds', text: '“Mayday, mayday, this is the ship—” and a voice answers. Six rounds out. Stay alive.', effect: { rescue: true } },
  },
  {
    id: 'beacon-2',
    rooms: ['airlock'],
    group: 'goal',
    step: { exit: 'beacon', step: 2 },
    label: 'Board the tug',
    desc: 'The rescue ship has docked. This ends the run.',
    icon: 'launch',
    noise: 0,
    when: (s) => s.progress.rescueIn === 0,
    clean: { sum: 'Escape', text: 'The inner door opens on a stranger in a vac suit, holding out a hand.', effect: { win: 'beacon' } },
  },
  {
    id: 'jump-0',
    work: 2,
    rooms: ['bridge'],
    group: 'goal',
    step: { exit: 'jump', step: 0 },
    flight: true,
    label: 'Plot the jump',
    desc: 'Set a course for home. Jump, step 1.',
    icon: 'map',
    stat: 'tech',
    noise: 0,
    clean: { sum: 'Done', text: 'The navigation solution locks. Home, forty days out.' },
    cost: { sum: 'Done, +1 stress', text: 'You get a solution. You are almost sure it is the right one.', effect: { stress: 1 } },
    fail: { sum: 'Noise', text: 'NAV ERROR, in a loud flat voice.', effect: { noise: 1 } },
  },
  {
    id: 'jump-1',
    work: 2,
    rooms: ['engineering'],
    group: 'goal',
    step: { exit: 'jump', step: 1 },
    label: 'Light the jump drive',
    desc: 'Jump, step 2. It is not quiet.',
    icon: 'power',
    stat: 'tech',
    noise: 2,
    clean: { sum: 'Done', text: 'The drive spins up with a sound like a cathedral organ.' },
    cost: { sum: 'Done, 1 damage', text: 'It comes up, and a pressure valve blows beside your head.', effect: { hp: -1 } },
    fail: { sum: 'Noise', text: 'It coughs and dies. Everything aboard heard it cough.', effect: { noise: 1 } },
  },
  {
    id: 'jump-2',
    rooms: ['cryo'],
    group: 'goal',
    step: { exit: 'jump', step: 2 },
    label: 'Go back under',
    desc: 'Climb into your pod before the jump. This ends the run.',
    icon: 'launch',
    noise: 0,
    clean: { sum: 'Escape', text: 'The lid comes down. The cold comes in. The drive fires.', effect: { win: 'jump' } },
  },
];
