import type { DiscoveryDef } from './cards';

// Drawn the first time you step into a room: turning over the tile.

export const DISCOVERIES: DiscoveryDef[] = [
  {
    id: 'quiet',
    weight: 5,
    title: 'Quiet',
    art: 'room',
    tone: 'calm',
    text: (c) => `Nothing moves in the ${c.room}. Just the hum of the ship and your own breathing. You let yourself believe it, for now.`,
  },
  {
    id: 'quiet-2',
    weight: 3,
    title: 'Empty',
    art: 'room',
    tone: 'calm',
    text: 'Whatever happened here happened a while ago. Dust has settled on the blood.',
  },
  {
    id: 'locker',
    weight: 4,
    title: 'An open locker',
    art: 'box',
    tone: 'good',
    text: 'A locker hangs open, half emptied by someone in a hurry. They missed something.',
    effect: { item: 'stim' },
  },
  {
    id: 'cache',
    weight: 3,
    title: 'Somebody’s stash',
    art: 'box',
    tone: 'good',
    text: 'Behind a loose panel, a go-bag. Someone packed it for exactly this and never made it back.',
    choices: [
      { label: 'Take the medkit', result: { text: 'You take the medkit and leave the rest.', effect: { item: 'medkit' } } },
      { label: 'Take the flare', result: { text: 'You take the flare. Light might matter more than bandages.', effect: { item: 'flare' } } },
    ],
  },
  {
    id: 'body',
    weight: 3,
    title: 'A body',
    art: 'body',
    tone: 'tense',
    text: 'A crew member, face down, one arm still reaching for the door. There is a bulge in their jumpsuit pocket.',
    choices: [
      {
        label: 'Search them',
        stat: 'wits',
        clean: { text: 'You find sealant foam, and you manage not to look at their face.', effect: { item: 'foam' } },
        cost: { text: 'Sealant foam. You turned them over to get it, and now you have seen their face.', effect: { item: 'foam', stress: 1 } },
        fail: { text: 'They are not quite as dead as they looked. They grab your wrist, sigh, and let go. For good this time.', effect: { stress: 2 } },
      },
      { label: 'Leave them be', result: { text: 'You step over them. Sorry.' } },
    ],
  },
  {
    id: 'dark',
    weight: 2,
    title: 'Lights out',
    art: 'dark',
    tone: 'tense',
    text: 'The lights here are smashed — deliberately, every one. The dark is total. Something wanted it this way.',
    effect: { hazard: { type: 'dark', where: 'here' }, stress: 1 },
  },
  {
    id: 'smoulder',
    weight: 1.5,
    title: 'Smouldering',
    art: 'fire',
    tone: 'danger',
    text: 'Smoke. A cable tray is smouldering, the insulation curling. Any second now it will catch.',
    choices: [
      {
        label: 'Beat it out',
        stat: 'might',
        clean: { text: 'You smother it with a jacket. Crisis averted.' },
        cost: { text: 'You get it, and burn your palms getting it.', effect: { hp: -1 } },
        fail: { text: 'It catches with a whump. You stagger back, singed.', effect: { hp: -1, hazard: { type: 'fire', where: 'here' } } },
      },
      { label: 'Back off and let it burn', result: { text: 'It catches. You are standing in a fire now.', effect: { hazard: { type: 'fire', where: 'here' } } } },
    ],
  },
  {
    id: 'tripwire',
    weight: 2,
    title: 'Tripwire',
    art: 'wire',
    tone: 'tense',
    text: 'Your boot touches a wire strung across the doorway at ankle height. Somebody rigged this. You freeze with your weight half on it.',
    choices: [
      {
        label: 'Disarm it',
        stat: 'tech',
        clean: { text: 'Pots and pans, tied to a pressure plate. You take the flare they used as a trigger.', effect: { item: 'flare' } },
        cost: { text: 'You get most of it. One pan hits the deck with a clang.', effect: { noise: 2 } },
        fail: { text: 'An avalanche of scrap metal. Everything aboard knows where you are.', effect: { noise: 3, hp: -1 } },
      },
    ],
  },
  {
    id: 'handprints',
    weight: 2,
    title: 'Handprints',
    art: 'wall',
    tone: 'strange',
    text: 'Bloody handprints climb the wall, cross the ceiling, and disappear into a vent. They are human handprints. That is the worst part.',
    effect: { stress: 1 },
  },
  {
    id: 'lying-in-wait',
    weight: 2,
    act: 2,
    title: 'It was waiting',
    art: 'eye',
    tone: 'danger',
    text: (c) => `It was waiting in here, in the dark, perfectly still. A ${c.brood} uncurls from the corner and turns toward you.`,
    effect: { spawn: { kind: 'brood', where: 'here' }, stress: 1 },
  },
  {
    id: 'barricade',
    weight: 2,
    title: 'A barricade',
    art: 'door',
    tone: 'strange',
    text: 'Somebody made a stand in here: furniture piled against the far hatch, a sleeping bag, empty cans. The barricade faces inward.',
    choices: [
      {
        label: 'Search the camp',
        stat: 'wits',
        clean: { text: 'A diary, and a shock baton wrapped in a blanket.', effect: { item: 'baton' } },
        cost: { text: 'Sedatives. The diary you leave shut.', effect: { item: 'sedative' } },
        fail: { text: 'Only the diary. You read the last page. You wish you hadn’t.', effect: { stress: 1 } },
      },
    ],
  },
  // Room-specific
  {
    id: 'autodoc',
    rooms: ['medbay'],
    weight: 6,
    title: 'The auto-doc',
    art: 'medbay',
    tone: 'good',
    text: 'The auto-doc wakes as you walk in, reads your vitals, and without asking seals the worst of your cuts with a hiss of spray.',
    effect: { hp: 1 },
  },
  {
    id: 'weapon-locker',
    rooms: ['armory', 'security'],
    weight: 6,
    title: 'Weapon locker',
    art: 'armory',
    tone: 'good',
    text: 'One locker still has its seal. Inside, cleaned and oiled and waiting: something that fires.',
    effect: { item: 'pistol' },
  },
  {
    id: 'still-warm',
    rooms: ['galley', 'quarters'],
    weight: 4,
    title: 'Still warm',
    art: 'room',
    tone: 'tense',
    text: 'A mug of coffee on the table. It is still warm. Somebody was here minutes ago.',
    effect: { stress: 1, diceNext: 1 },
  },
  {
    id: 'stars',
    rooms: ['observation', 'bridge'],
    weight: 4,
    title: 'The view',
    art: 'observation',
    tone: 'calm',
    text: 'Through the glass, a planet turns below: blue and white and utterly indifferent. It makes you feel small in a way that helps.',
    effect: { stress: -1 },
  },
  {
    id: 'jars',
    rooms: ['lab', 'nest'],
    weight: 4,
    title: 'Specimen jars',
    art: 'lab',
    tone: 'strange',
    text: 'Rows of jars, labelled in a neat hand. The contents of the last three are labelled with crew names.',
    effect: { stress: 1, clue: true },
  },
  {
    id: 'toolbox',
    rooms: ['engineering', 'maintenance', 'hangar'],
    weight: 4,
    title: 'A proper toolbox',
    art: 'box',
    tone: 'good',
    text: 'A red rolling toolbox, every drawer labelled, nothing missing. The owner cared about this more than anything.',
    effect: { item: 'toolkit' },
  },
];
