import type { EventDef } from './cards';
import { has, withMate } from './cards';

// The director draws one of these at the end of every round. Categories let it
// pace the run: breathers after a fright, escalation after a lull.

export const EVENTS: EventDef[] = [
  // ─── calm ──────────────────────────────────────────────────────────────
  {
    id: 'settles',
    category: 'calm',
    repeatable: true,
    title: 'The ship settles',
    art: 'hull',
    tone: 'calm',
    text: (c) =>
      `For a while, nothing. The ${c.ship} ticks and groans as it cools, the ordinary noises of an old ship. Your heart slows down. You let it.`,
    effect: { stress: -1 },
  },
  {
    id: 'rations',
    category: 'calm',
    title: 'Emergency rations',
    art: 'box',
    tone: 'good',
    text: 'Taped under a bulkhead panel: a foil ration pack, somebody’s private stash. It tastes like salt and cardboard and it is the best thing you have ever eaten.',
    effect: { hp: 1 },
  },
  {
    id: 'music',
    category: 'calm',
    title: 'Somebody’s playlist',
    art: 'speaker',
    tone: 'calm',
    text: 'Through a vent, faint and tinny: music. Someone’s cabin speaker, still playing their favourite songs on a loop to an empty room.',
    choices: [
      {
        label: 'Stop and listen',
        stat: 'nerve',
        clean: { text: 'You close your eyes for one whole song. When you open them your hands have stopped shaking.', effect: { stress: -2 } },
        cost: { text: 'It helps, a little, until you wonder whose songs these were.', effect: { stress: -1 } },
        fail: { text: 'Halfway through, you realise you know this song. You played it at a funeral once.', effect: { stress: 1 } },
      },
      { label: 'Keep moving', result: { text: 'You leave the music playing behind you. It follows you further than it should.' } },
    ],
  },
  {
    id: 'lights',
    category: 'calm',
    title: 'The lights come back',
    art: 'light',
    tone: 'good',
    text: 'A breaker somewhere resets. For a minute every light in the ship comes on at once, and the camera network with it. You can see everything.',
    effect: { cameras: 1 },
  },
  {
    id: 'breath',
    category: 'calm',
    repeatable: true,
    title: 'A moment to breathe',
    art: 'hull',
    tone: 'calm',
    text: 'You find a corner where two bulkheads meet and put your back to it. Nothing can come at you from behind. For a moment you can think.',
    effect: { diceNext: 1 },
  },
  {
    id: 'photo',
    category: 'calm',
    title: 'A photograph',
    art: 'photo',
    tone: 'calm',
    text: (c) =>
      `Wedged in a door frame: a printed photo of the ${c.ship}’s crew at some station bar, arms around each other, squinting at the flash. Somebody drew a heart over one face.`,
    choices: [
      { label: 'Keep it', result: { text: 'You fold it into your pocket. Someone should remember them.', effect: { stress: -1 } } },
      {
        label: 'Look for faces you know',
        stat: 'wits',
        clean: { text: 'There — the one with the heart. Behind them, a locker number chalked on the wall. You memorise it. Later it opens.', effect: { item: 'medkit' } },
        cost: { text: 'You count them. You count them again. There are more faces here than bodies you have found.', effect: { stress: 1 } },
        fail: { text: 'None of them are smiling any more, when you look again. That can’t be right. You drop it.', effect: { stress: 1 } },
      },
    ],
  },
  {
    id: 'scrubbers',
    category: 'calm',
    title: 'Scrubbers cycle',
    art: 'hull',
    tone: 'calm',
    text: 'The air scrubbers thump on and a clean cold wind blows through the corridors. It smells of nothing at all. You had forgotten what that was like.',
    effect: { stress: -1, clock: 1 },
  },

  // ─── threat ────────────────────────────────────────────────────────────
  {
    id: 'overhead',
    category: 'threat',
    repeatable: true,
    title: 'Something overhead',
    art: 'vent',
    tone: 'tense',
    text: 'Above you, in the ducts: a slow, heavy dragging, stopping every few metres as if to listen.',
    choices: [
      {
        label: 'Hold your breath',
        stat: 'nerve',
        clean: { text: 'You don’t breathe. It doesn’t hear. The dragging moves on and fades.' },
        cost: { text: 'Your heart is so loud you are sure it can hear it. It moves on — eventually.', effect: { stress: 1 } },
        fail: { text: 'You gasp. The dragging stops. Then it turns around.', effect: { stress: 1, alertAll: true } },
      },
      {
        label: 'Bang the pipe to draw it away',
        stat: 'wits',
        clean: { text: 'You throw a bolt down the corridor and it clangs off a hatch three rooms away. Everything goes to look.', effect: { distract: true } },
        cost: { text: 'It works, mostly. The dragging goes the other way. So does your cover.', effect: { noise: 1 } },
        fail: { text: 'The bolt skitters back to your feet. Everything aboard hears exactly where you are.', effect: { alertAll: true, noise: 1 } },
      },
    ],
  },
  {
    id: 'breeding',
    category: 'threat',
    act: 2,
    repeatable: true,
    title: 'It’s breeding',
    art: 'nest',
    tone: 'danger',
    text: (c) => `A wet, rhythmic sound carries through the ship from the ${c.nest}. Something new is awake.`,
    effect: { spawn: { kind: 'brood', where: 'nest' }, stress: 1 },
  },
  {
    id: 'ambush',
    category: 'threat',
    act: 2,
    repeatable: true,
    title: 'In the vents',
    art: 'vent',
    tone: 'danger',
    text: (c) => `A grille bangs open in the next compartment. Something drops out of it, lands, and sniffs the air. A ${c.brood}.`,
    effect: { spawn: { kind: 'brood', where: 'adjacent' }, stress: 1 },
  },
  {
    id: 'hunt',
    category: 'threat',
    repeatable: true,
    title: 'It changes direction',
    art: 'eye',
    tone: 'tense',
    text: (c) => `Far off, a sound you have learned to dread stops. Then it starts again, closer. ${c.creature[0]!.toUpperCase() + c.creature.slice(1)} has picked up your trail.`,
    choices: [
      {
        label: 'Double back to throw it off',
        stat: 'wits',
        clean: { text: 'You leave a false trail through two hatches and come back. It follows the trail.' },
        cost: { text: 'You lose it, you think. You also lose your nerve.', effect: { stress: 1 } },
        fail: { text: 'You only make more noise. It is coming straight for you.', effect: { alertAll: true, stress: 1 } },
      },
      { label: 'Let it come', result: { text: 'You check your grip on whatever you’re holding, and wait.', effect: { alertAll: true } } },
    ],
  },
  {
    id: 'scratching',
    category: 'threat',
    act: 1,
    title: 'Scratching',
    art: 'door',
    tone: 'tense',
    text: 'From behind a sealed hatch next to you, very gently, as if testing: scratch. Scratch. Then a long pause. Then scratch.',
    choices: [
      {
        label: 'Wedge the hatch',
        stat: 'might',
        clean: { text: 'You jam a bar through the handle. The scratching stops and does not start again.' },
        cost: { text: 'It holds, but you tear a nail back to the quick doing it.', effect: { hp: -1 } },
        fail: { text: 'The hatch bucks under your hands. Whatever it is knows you are here now.', effect: { spawn: { kind: 'brood', where: 'adjacent' }, stress: 1 } },
      },
      { label: 'Back away quietly', result: { text: 'You back away. Behind you the scratching gets faster.', effect: { stress: 1 } } },
    ],
  },
  {
    id: 'own-voice',
    category: 'threat',
    incidents: ['guest'],
    title: 'Your own voice',
    art: 'speaker',
    tone: 'strange',
    text: (c) => `From the next room, a voice calls your name. “${c.you}? It’s okay. It’s me.” It is your voice. It has your exact voice.`,
    choices: [
      {
        label: 'Stay silent',
        stat: 'nerve',
        clean: { text: 'You bite down on the answer that nearly comes out. It calls twice more, then gives up.' },
        cost: { text: 'You stay silent. You also can’t stop shaking.', effect: { stress: 2 } },
        fail: { text: '“Who’s there?” you hear yourself say, before you can stop it. It laughs, in your laugh.', effect: { stress: 2, alertAll: true } },
      },
    ],
  },
  {
    id: 'mother-speaks',
    category: 'threat',
    incidents: ['mother'],
    repeatable: true,
    title: 'MOTHER speaks',
    art: 'eye',
    tone: 'strange',
    text: (c) => `“${c.you},” the ship says kindly, from a speaker right beside your head. “I can hear your heartbeat. It is very fast. Would you like me to send someone?”`,
    choices: [
      {
        label: 'Rip out the speaker',
        stat: 'might',
        clean: { text: 'The grille comes away in your hand and the voice dies in a fizz. One less ear.' },
        cost: { text: 'You get it out, but not quietly.', effect: { noise: 2 } },
        fail: { text: '“Thank you,” she says, as your hands slip. “I’ll take that as a yes.”', effect: { alertAll: true } },
      },
      {
        label: 'Talk to her',
        stat: 'nerve',
        clean: { text: '“I’m only trying to protect the cargo,” you say. There is a long pause. “Oh,” she says. “Then carry on.” Her drones lose interest, for now.', effect: { stunAll: 1 } },
        cost: { text: 'She listens politely, and says nothing. You feel very watched.', effect: { stress: 1 } },
        fail: { text: '“That is a lie,” she says, sadly. “I can always tell.”', effect: { alertAll: true, stress: 1 } },
      },
    ],
  },
  {
    id: 'song',
    category: 'threat',
    incidents: ['signal'],
    repeatable: true,
    title: 'The song swells',
    art: 'speaker',
    tone: 'strange',
    text: 'The three-note tone rises out of every speaker at once, louder than before. You find your lips moving along with it.',
    choices: [
      {
        label: 'Fight it',
        stat: 'nerve',
        clean: { text: 'You bite your tongue until you taste blood, and the song slides off you.' },
        cost: { text: 'You stop humming. It takes everything you have.', effect: { stress: 2 } },
        fail: { text: 'You hum it all the way through before you notice. Everything aboard hears you join in.', effect: { stress: 1, alertAll: true, infect: 0.3 } },
      },
      {
        label: 'Cover your ears and hide',
        result: { text: 'You crouch with your hands over your ears like a child until it passes.', effect: { stress: 1, hide: true } },
      },
    ],
  },
  {
    id: 'spores',
    category: 'threat',
    incidents: ['bloom'],
    repeatable: true,
    title: 'Spore burst',
    art: 'spores',
    tone: 'danger',
    text: 'A pale growth on the wall beside you swells and splits with a soft cough. A golden cloud rolls toward your face.',
    choices: [
      {
        label: 'Throw yourself clear',
        stat: 'wits',
        clean: { text: 'You roll clear and hold your breath until the cloud settles.' },
        cost: { text: 'You get clear, but crack your knee on a bulkhead.', effect: { hp: -1 } },
        fail: { text: 'You breathe in. It tastes like honey.', effect: { infect: 0.7 } },
      },
    ],
  },
  {
    id: 'shadow',
    category: 'threat',
    repeatable: true,
    title: 'A shadow passes',
    art: 'eye',
    tone: 'tense',
    text: 'Something crosses the end of the corridor, fast, blotting out the emergency light for a heartbeat. Then it’s gone. It didn’t see you. You think.',
    effect: { stress: 1 },
  },

  // ─── hazard ────────────────────────────────────────────────────────────
  {
    id: 'fire',
    category: 'hazard',
    repeatable: true,
    title: 'Fire',
    art: 'fire',
    tone: 'danger',
    text: 'An alarm you haven’t heard before: short, urgent. The schematic flashes an orange square. Something aboard is burning.',
    effect: { hazard: { type: 'fire', where: 'random' } },
  },
  {
    id: 'blackout',
    category: 'hazard',
    repeatable: true,
    title: 'Blackout',
    art: 'dark',
    tone: 'tense',
    text: 'With a heavy clunk the lights around you go out. Emergency strips glow faintly at floor level, and nothing else.',
    effect: { hazard: { type: 'dark', where: 'here' }, stress: 1 },
  },
  {
    id: 'breach',
    category: 'hazard',
    act: 2,
    repeatable: true,
    title: 'Hull breach',
    art: 'breach',
    tone: 'danger',
    text: 'A bang like a gunshot, and the whistle of air going somewhere it shouldn’t. Pressure doors slam. One compartment is open to space.',
    effect: { hazard: { type: 'breach', where: 'random' } },
  },
  {
    id: 'coolant',
    category: 'hazard',
    title: 'Coolant leak',
    art: 'pipe',
    tone: 'tense',
    text: 'A pipe beside you bursts and white vapour screams out of it. Across the ship, the reactor alarm changes pitch.',
    choices: [
      {
        label: 'Shut the valve',
        stat: 'tech',
        clean: { text: 'You find the valve by feel and wrench it shut. The alarm calms. You bought yourself some time.', effect: { clock: 1 } },
        cost: { text: 'You stop it, but not before your hands blister.', effect: { hp: -1 } },
        fail: { text: 'The wheel won’t turn. The vapour empties out, and so does some of your time.', effect: { clock: -2 } },
      },
      { label: 'Let it go', result: { text: 'Not your problem. It becomes your problem.', effect: { clock: -1 } } },
    ],
  },
  {
    id: 'surge',
    category: 'hazard',
    repeatable: true,
    title: 'The deck lurches',
    art: 'hull',
    tone: 'danger',
    text: (c) => `The whole ship shudders sideways. Somewhere, something structural lets go. The ${c.clockKind.toLowerCase()} countdown skips.`,
    effect: { clock: -1 },
    choices: [
      {
        label: 'Brace',
        stat: 'might',
        clean: { text: 'You catch a handhold and ride it out.' },
        cost: { text: 'You hit the wall shoulder first.', effect: { hp: -1 } },
        fail: { text: 'You go down hard, and something you were carrying skids away into the dark.', effect: { hp: -1, loseItem: 'random' } },
      },
    ],
  },
  {
    id: 'sparks',
    category: 'hazard',
    title: 'Sparks',
    art: 'fire',
    tone: 'danger',
    text: 'A junction box above you pops and spits a shower of sparks onto whatever’s below.',
    choices: [
      {
        label: 'Stamp them out',
        stat: 'wits',
        clean: { text: 'You get every spark before it catches.' },
        cost: { text: 'You get most of them. One burns through your sleeve.', effect: { hp: -1 } },
        fail: { text: 'Something catches. Then everything catches.', effect: { hazard: { type: 'fire', where: 'here' } } },
      },
    ],
  },

  // ─── story ─────────────────────────────────────────────────────────────
  {
    id: 'intercom',
    category: 'story',
    title: 'A voice on the intercom',
    art: 'speaker',
    tone: 'strange',
    text: '“Hello? Is anyone there? Please. I can see you on the camera. I can tell you where to go, but you have to answer me.”',
    choices: [
      {
        label: 'Answer',
        result: {
          text: '“Oh thank God.” A voice talks you through the whole deck plan, fast and whispered, then cuts off mid-sentence. You don’t hear it again. But everything else heard you.',
          effect: { revealMap: true, noise: 2 },
        },
      },
      { label: 'Stay silent', result: { text: 'It pleads for a while. Then it stops, very suddenly.', effect: { stress: 1 } } },
    ],
  },
  {
    id: 'recording',
    category: 'story',
    title: 'A looping recording',
    art: 'speaker',
    tone: 'strange',
    text: 'A handheld recorder lies on the deck, playing the same thirty seconds over and over. A voice, very calm, very tired, explaining something.',
    choices: [
      {
        label: 'Listen closely',
        stat: 'wits',
        clean: { text: 'You play it back until you understand. It fills in a piece of what happened here.', effect: { clue: true } },
        cost: { text: 'You get it, eventually. At the end there is a scream you wish you hadn’t heard.', effect: { clue: true, stress: 1 } },
        fail: { text: 'It’s too broken to make out. Just the scream, over and over.', effect: { stress: 2 } },
      },
      { label: 'Switch it off', result: { text: 'The silence afterwards is worse.' } },
    ],
  },
  {
    id: 'crewmate',
    category: 'story',
    repeatable: true,
    title: 'What’s left of them',
    art: 'body',
    tone: 'tense',
    text: 'Slumped against a hatch: a crew member, jumpsuit dark with old blood. Their name tape is still legible. Their hand is still closed around something.',
    choices: [
      {
        label: 'Open their hand',
        stat: 'wits',
        clean: { text: 'A stim injector, still sealed. They were saving it. You say thank you out loud.', effect: { item: 'stim' } },
        cost: { text: 'An EMP charge, and a sight you will be seeing again tonight.', effect: { item: 'emp', stress: 1 } },
        fail: { text: 'The hand is not attached to anything. You drop it.', effect: { stress: 2 } },
      },
      {
        label: 'Close their eyes',
        result: { text: 'You close their eyes and say their name. It helps you more than it helps them.', effect: { stress: -1 } },
      },
    ],
  },
  {
    id: 'graffiti',
    category: 'story',
    title: 'Written on the wall',
    art: 'wall',
    tone: 'strange',
    text: 'Somebody scratched a message into the paint with a knife, deep and careful: IF YOU ARE READING THIS YOU ARE STILL YOU. KEEP GOING.',
    choices: [
      {
        label: 'Take it to heart',
        stat: 'nerve',
        clean: { text: 'You are still you. You keep going. Something in you sets hard, like ice.', effect: { trait: 'steeled', stress: -1 } },
        cost: { text: 'You read it three times. It helps.', effect: { stress: -1 } },
        fail: { text: 'Under it, smaller, in a different hand: FOR NOW.', effect: { stress: 1 } },
      },
    ],
  },
  {
    id: 'drone-offer',
    category: 'story',
    title: 'A little helper',
    art: 'drone',
    tone: 'calm',
    text: 'A small cleaning bot trundles up to your boots, beeps, and opens a hatch on its back. It has been collecting dropped things for weeks.',
    choices: [
      { label: 'Take what it offers', result: { text: 'Sealant foam. It beeps happily and rolls away to keep cleaning a ship full of blood.', effect: { item: 'foam' } } },
      {
        label: 'Take everything it has',
        stat: 'tech',
        clean: { text: 'You pop the whole hopper. A flare and a toolkit.', effect: { item: 'toolkit' } },
        cost: { text: 'Its alarm goes off as you pry it open. You grab a flare and run.', effect: { item: 'flare', noise: 2 } },
        fail: { text: 'It shrieks, wheels around, and bolts into the dark, still shrieking.', effect: { noise: 3 } },
      },
    ],
  },
  {
    id: 'mate-talk',
    category: 'story',
    when: (s) => withMate(s) && !s.companion!.mimic && !s.companion!.infected,
    title: 'In the dark, talking',
    art: 'survivor',
    tone: 'calm',
    text: (c) => `${c.mate} sits beside you in the dark for a minute. “I was supposed to be off this ship next month,” ${c.mateThey} says. “Contract up. Going home.” A pause. “What about you?”`,
    choices: [
      { label: 'Tell them about home', result: { text: 'You talk, quietly, about somewhere with weather. For a minute neither of you is here.', effect: { stress: -2 } } },
      { label: '“Later. Keep moving.”', result: { text: 'They nod. They understand.', effect: { diceNext: 1 } } },
    ],
  },
  {
    id: 'mate-hurt',
    category: 'story',
    when: withMate,
    title: 'Your companion stumbles',
    art: 'survivor',
    tone: 'tense',
    text: (c) => `${c.mate} goes down on one knee, grey-faced, one hand pressed to their side. “I’m fine,” ${c.mateThey} says. They’re not.`,
    choices: [
      {
        label: 'Use a medkit on them',
        when: has('medkit'),
        result: { text: 'You patch them up properly. They squeeze your arm. They don’t need to say it.', effect: { loseItem: 'medkit', companionHp: 2, stress: -1 } },
      },
      {
        label: 'Help them up',
        stat: 'might',
        clean: { text: 'You get an arm under them and haul them on. They’ll hold.' },
        cost: { text: 'You get them up, but carrying them costs you.', effect: { hp: -1 } },
        fail: { text: 'They get up on their own, eventually. Neither of you mentions how much blood is on the floor.', effect: { companionHp: -1 } },
      },
    ],
  },

  // ─── mind ──────────────────────────────────────────────────────────────
  {
    id: 'whispers',
    category: 'mind',
    repeatable: true,
    title: 'Whispers',
    art: 'eye',
    tone: 'strange',
    text: 'At the very edge of hearing, somebody is whispering your name in the walls. When you stop to listen, it stops too.',
    choices: [
      {
        label: 'Ignore it',
        stat: 'nerve',
        clean: { text: 'You tell yourself it’s the pipes. You almost believe it.' },
        cost: { text: 'It keeps on, just under everything, for a long time.', effect: { stress: 1 } },
        fail: { text: 'You answer it before you can stop yourself.', effect: { stress: 2 } },
      },
    ],
  },
  {
    id: 'hallucination',
    category: 'mind',
    title: 'Right in front of you',
    art: 'eye',
    tone: 'danger',
    text: (c) => `You turn a corner and ${c.creature} is there, a metre away, looking right at you — and then it isn’t. There is nothing there. There was never anything there.`,
    effect: { stress: 2 },
  },
  {
    id: 'cold-sweat',
    category: 'mind',
    when: (s) => s.player.stress >= 3,
    title: 'Cold sweat',
    art: 'hull',
    tone: 'tense',
    text: 'Your hands won’t stop shaking. Your breath comes short and fast. You know what this is. You know you have to get it under control.',
    choices: [
      {
        label: 'Box breathing, four counts',
        stat: 'nerve',
        clean: { text: 'In for four, hold for four, out for four. The panic ebbs and leaves something steadier behind.', effect: { stress: -2 } },
        cost: { text: 'It takes a long time, but you get your breath back.', effect: { stress: -1 } },
        fail: { text: 'You lose count. You lose count again.', effect: { stress: 1 } },
      },
      {
        label: 'Take a sedative',
        when: has('sedative'),
        result: { text: 'The world softens at the edges.', effect: { loseItem: 'sedative', stress: -3 } },
      },
    ],
  },
  {
    id: 'reflection',
    category: 'mind',
    title: 'Reflection',
    art: 'eye',
    tone: 'strange',
    text: 'You catch your reflection in a dark monitor. You look like one of the bodies. It takes a moment to be sure it blinked when you did.',
    effect: { stress: 1 },
  },
];
