import { BAG_THREATS, MAP, NODE_IDS, RULES, THREATS, VENT_NODES, depthDef, threatDef } from './content';
import { blankLine, hiveLine, motherWakes, spawnLine, where } from './voice';
import { holding } from './deck';
import { distance } from './graph';
import { nextInt } from './rng';
import { boardCap, hiveWake, noiseFloor } from './state';
import type { GameState, Location, NodeId, Threat, ThreatType, TokenType } from './types';

export function tokensInBag(state: GameState): number {
  return (Object.values(state.bag) as number[]).reduce((a, b) => a + b, 0);
}

export function tokensInReserve(state: GameState): number {
  return (Object.values(state.reserve) as number[]).reduce((a, b) => a + b, 0);
}

/** COLD SWEAT in hand makes everything the player does one louder. */
export function noiseModifier(state: GameState): number {
  return holding(state, 'inf_sweat') ? 1 : 0;
}

export function addNoise(state: GameState, id: NodeId, n: number): void {
  if (n === 0) return;
  const floor = noiseFloor(state.depth, id);
  const value = (state.ship.noise[id] ?? 0) + n;
  state.ship.noise[id] = Math.max(floor, Math.min(RULES.noiseMax, value));
}

/** Noise generated by a player action, including the infection surcharge. */
export function playerNoise(state: GameState, base: number): number {
  if (base <= 0) return 0;
  return base + noiseModifier(state);
}

/** Where a threat stands, for the purposes of measuring distance. */
export function whereabouts(state: GameState, t: Threat): NodeId {
  if (t.node !== 'vents') return t.node;
  // In the ducts it is everywhere and nowhere; measure from the nearest hatch.
  let best = VENT_NODES[0] as NodeId;
  let bestD = Infinity;
  for (const v of VENT_NODES) {
    const d = t.target === null ? 0 : distance(state, v, t.target, false);
    if (d < bestD) {
      bestD = d;
      best = v;
    }
  }
  return best;
}

/**
 * How far a sound of this many points carries to this creature. Loud actions
 * reach further; each creature has a ceiling on what it can pick out at all.
 * This is the whole of the stealth game: a sound is a place, not an alarm.
 */
export function earshot(type: ThreatType, volume: number): number {
  const def = threatDef(type);
  if (def.behaviour === 'mother') return volume > 0 ? 99 : 0;
  return Math.min(def.hearing, volume);
}

/**
 * Something made a noise at `at`. Everything that can hear it now believes the
 * player is there, and goes to look. Nothing is told where the player actually
 * is — which is what makes creeping, luring and doubling back worth anything.
 */
export function alert(state: GameState, at: NodeId, volume: number): void {
  if (volume <= 0) return;
  for (const t of state.threats) {
    const from = whereabouts(state, t);
    const d = distance(state, from, at, false);
    if (d <= earshot(t.type, volume)) {
      t.target = at;
      t.stance = 'hunting';
      t.cold = 0;
    }
  }
}

/** A player action's noise: it lands in the compartment and it is heard. */
export function makeNoise(state: GameState, base: number): void {
  if (state.player.node === 'vents') return;
  const volume = playerNoise(state, base);
  if (volume <= 0) return;
  addNoise(state, state.player.node, volume);
  alert(state, state.player.node, volume);
}

/** Something loud, somewhere else, on purpose. */
export function lureAt(state: GameState, at: NodeId, volume: number): number {
  addNoise(state, at, volume);
  const before = state.threats.filter((t) => t.target === at).length;
  alert(state, at, volume);
  return state.threats.filter((t) => t.target === at).length - before;
}

export function spawnThreat(state: GameState, type: ThreatType, at: Location): Threat {
  const def = threatDef(type);
  const id = `t${state.nextThreatId}`;
  state.nextThreatId += 1;
  const t: Threat = {
    id,
    type,
    node: at,
    hp: def.hp,
    // It arrives because it heard something here, so here is what it knows.
    target: at === 'vents' ? null : at,
    stance: at === 'vents' ? 'wandering' : 'hunting',
    cold: 0,
    stalled: 0,
    seenNode: null,
    seenTurn: -1,
  };
  state.threats.push(t);
  state.feed.push({ turn: state.turn, kind: 'threat', text: spawnLine(state, type, at) });
  return t;
}

/** Everything on the board that came out of the bag. The MOTHER did not. */
export function boardCount(state: GameState): number {
  return state.threats.filter((t) => t.type !== 'mother').length;
}

/**
 * The hive reading. It only ever goes up, and when it fills, the thing in the
 * hold gets up. Escalation feeds it, so a capped board is not a safe board.
 */
export function advanceHive(state: GameState, n: number): void {
  if (n <= 0 || state.ship.motherWoken) return;
  const wake = hiveWake(state.depth);
  const before = state.ship.hive;
  state.ship.hive = Math.min(wake, state.ship.hive + n);
  const line = hiveLine(state, before, state.ship.hive, wake);
  if (line !== null) state.feed.push({ turn: state.turn, kind: 'alarm', text: line });
  if (state.ship.hive >= wake) wakeMother(state);
}

export function wakeMother(state: GameState): void {
  if (state.ship.motherWoken) return;
  state.ship.motherWoken = true;
  const t = spawnThreat(state, 'mother', MAP.nest);
  t.target = state.player.node === 'vents' ? MAP.nest : state.player.node;
  state.feed.push({ turn: state.turn, kind: 'alarm', text: motherWakes(state) });
}

/**
 * The board is full, so the bag makes the ship worse instead of busier: a STRAY
 * grows into a HUNTER, and when there is nothing left to grow, the hive stirs.
 * §3.3 — pressure keeps climbing, the count does not.
 */
export function escalate(state: GameState, at: NodeId): void {
  const strays = state.threats.filter((t) => t.type === 'contact');
  const hunters = state.threats.filter((t) => t.type === 'drifter').length;
  // Never turn the whole board into HUNTERS. A ship with three of them on it is
  // the crowd this rework exists to delete; keep a mix and push the rest of the
  // pressure into the hold instead.
  const stray = strays.length > hunters ? strays[0] : undefined;
  const haveDrifter = (state.bag.drifter ?? 0) > 0 || (state.reserve.drifter ?? 0) > 0;
  if (stray !== undefined && haveDrifter) {
    if ((state.bag.drifter ?? 0) > 0) state.bag.drifter -= 1;
    else state.reserve.drifter -= 1;
    state.bag.contact = (state.bag.contact ?? 0) + 1;
    stray.type = 'drifter';
    stray.hp = threatDef('drifter').hp;
    stray.target = at;
    stray.stance = 'hunting';
    stray.cold = 0;
    state.feed.push({
      turn: state.turn,
      kind: 'alarm',
      text:
        `>> The STRAY in ${where(stray.node)} has grown into a HUNTER. There are no more of ` +
        'them aboard than there were an hour ago. There is worse.',
    });
    advanceHive(state, RULES.hivePerEscalation);
    return;
  }
  state.feed.push({
    turn: state.turn,
    kind: 'alarm',
    text: '>> Nothing new comes. Something old wakes up further in, and the hold answers it.',
  });
  advanceHive(state, RULES.hivePerEscalation + 1);
}

/** Weighted pick of one token type out of the bag. */
function pickToken(state: GameState): TokenType | undefined {
  const total = tokensInBag(state);
  if (total === 0) return undefined;
  const [roll, rng] = nextInt(state.rng, total);
  state.rng = rng;
  let acc = 0;
  for (const t of ['blank', ...BAG_THREATS] as TokenType[]) {
    acc += state.bag[t] ?? 0;
    if (roll < acc) return t;
  }
  return undefined;
}

/**
 * Pull one token and resolve it at `at`. Blanks go back in the bag and drag a
 * STRAY out of the reserve with them: a quiet run is not a free run. A full
 * board escalates instead of spawning.
 */
export function bagDraw(state: GameState, at: Location): TokenType | 'capped' | 'empty' {
  state.stats.bagDraws += 1;
  const here: NodeId = at === 'vents' ? MAP.nest : at;
  if (boardCount(state) >= boardCap(state.depth)) {
    escalate(state, here);
    return 'capped';
  }
  const token = pickToken(state);
  if (token === undefined) {
    escalate(state, here);
    return 'empty';
  }
  if (token === 'blank') {
    const moved = Math.min(THREATS.blankEscalation, state.reserve.contact ?? 0);
    state.reserve.contact -= moved;
    state.bag.contact = (state.bag.contact ?? 0) + moved;
    state.feed.push({ turn: state.turn, kind: 'sys', text: blankLine(state, moved > 0) });
    return 'blank';
  }
  state.bag[token] = (state.bag[token] ?? 0) - 1;
  spawnThreat(state, token, at);
  return token;
}

/**
 * Any compartment at or above the threshold draws, then resets to its floor.
 * Canonical node order, so it is reproducible.
 */
export function noisePhase(state: GameState): void {
  for (const id of NODE_IDS) {
    if ((state.ship.noise[id] ?? 0) >= RULES.noiseThreshold) {
      bagDraw(state, id);
      if (id === MAP.nest) advanceHive(state, RULES.hivePerNestDraw);
      state.ship.noise[id] = noiseFloor(state.depth, id);
    }
  }
}

/** Which compartments will draw if the hour ends as it stands. */
export function nodesAtThreshold(state: GameState): NodeId[] {
  return NODE_IDS.filter((id) => (state.ship.noise[id] ?? 0) >= RULES.noiseThreshold);
}

/**
 * Decay: every compartment quietens by one, never below its floor. The nest is
 * the exception — it breathes, so the ship gets worse even when the player does
 * nothing at all.
 */
export function decayNoise(state: GameState): void {
  for (const id of NODE_IDS) {
    const floor = noiseFloor(state.depth, id);
    state.ship.noise[id] = Math.max(floor, (state.ship.noise[id] ?? 0) - RULES.noiseDecay);
  }
  if (state.turn % THREATS.nestNoise.everyTurns === 0) {
    addNoise(state, MAP.nest, depthDef(state.depth).nestNoiseAmount ?? THREATS.nestNoise.amount);
  }
}

export const NEST: NodeId = MAP.nest;
