import { MAP, NODE_IDS, RULES, THREATS, depthDef, threatDef } from './content';
import { blankLine, spawnLine } from './voice';
import { cardIdOf } from './deck';
import { nextInt } from './rng';
import { noiseFloor } from './state';
import type { GameState, NodeId, ThreatType, TokenType } from './types';

export function tokensInBag(state: GameState): number {
  return (Object.values(state.bag) as number[]).reduce((a, b) => a + b, 0);
}

export function tokensInReserve(state: GameState): number {
  return (Object.values(state.reserve) as number[]).reduce((a, b) => a + b, 0);
}

/** COLD SWEAT in hand makes everything the player does one louder (§5.3). */
export function noiseModifier(state: GameState): number {
  return state.player.hand.some((u) => cardIdOf(u) === 'panic_sweat') ? 1 : 0;
}

export function addNoise(state: GameState, id: NodeId, n: number): void {
  if (n === 0) return;
  const floor = noiseFloor(state.depth, id);
  const value = (state.ship.noise[id] ?? 0) + n;
  state.ship.noise[id] = Math.max(floor, Math.min(RULES.noiseMax, value));
}

/** Noise generated by a player action, including the panic surcharge. */
export function playerNoise(state: GameState, base: number): number {
  if (base <= 0) return 0;
  return base + noiseModifier(state);
}

export function makeNoise(state: GameState, base: number): void {
  if (state.player.node === 'vents') return;
  addNoise(state, state.player.node, playerNoise(state, base));
}

export function spawnThreat(state: GameState, type: ThreatType, at: NodeId | 'vents'): void {
  const def = threatDef(type);
  const id = `t${state.nextThreatId}`;
  state.nextThreatId += 1;
  state.threats.push({ id, type, node: at, hp: def.hp });
  state.feed.push({ turn: state.turn, kind: 'threat', text: spawnLine(state, type, at) });
}

/** Weighted pick of one token type out of the bag. */
function pickToken(state: GameState): TokenType | undefined {
  const total = tokensInBag(state);
  if (total === 0) return undefined;
  const [roll, rng] = nextInt(state.rng, total);
  state.rng = rng;
  let acc = 0;
  for (const t of ['blank', 'contact', 'drifter', 'burrower', 'chorus'] as TokenType[]) {
    acc += state.bag[t] ?? 0;
    if (roll < acc) return t;
  }
  return undefined;
}

/**
 * §4.7. Pull one token and resolve it at `at`.
 * Blanks go back in the bag and drag a Contact out of the reserve with them:
 * a quiet run is not a free run.
 */
export function bagDraw(state: GameState, at: NodeId | 'vents'): TokenType | 'empty' {
  state.stats.bagDraws += 1;
  const token = pickToken(state);
  if (token === undefined) {
    if ((state.reserve.contact ?? 0) > 0) {
      state.reserve.contact -= 1;
      spawnThreat(state, 'contact', at);
      state.feed.push({ turn: state.turn, kind: 'alarm', text: '>> SOMETHING THAT WAS NOT ABOARD BEFORE WALKS IN.' });
      return 'contact';
    }
    state.feed.push({
      turn: state.turn,
      kind: 'alarm',
      text: '>> NOTHING LEFT UNACCOUNTED FOR. EVERYTHING ABOARD MOVES AGAIN.',
    });
    return 'empty';
  }
  if (token === 'blank') {
    const moved = Math.min(THREATS.blankEscalation, state.reserve.contact ?? 0);
    state.reserve.contact -= moved;
    state.bag.contact = (state.bag.contact ?? 0) + moved;
    state.feed.push({ turn: state.turn, kind: 'sys', text: blankLine(state, moved > 0) });
    return 'blank';
  }
  state.bag[token] = (state.bag[token] ?? 0) - 1;
  spawnThreat(state, token, at);
  return token;
}

/**
 * §4.6 noise phase. Any node at or above the threshold draws, then resets to
 * its floor. Canonical node order, so it is reproducible.
 */
export function noisePhase(state: GameState): { extraActivation: boolean } {
  let extraActivation = false;
  for (const id of NODE_IDS) {
    if ((state.ship.noise[id] ?? 0) >= RULES.noiseThreshold) {
      const result = bagDraw(state, id);
      if (result === 'empty') extraActivation = true;
      state.ship.noise[id] = noiseFloor(state.depth, id);
    }
  }
  return { extraActivation };
}

/**
 * §4.6 decay: every node quietens by one, never below its floor.
 * The nest is the exception — it breathes, so the ship gets worse even when
 * the player does nothing at all. Without this a silent run faces no pressure.
 */
export function decayNoise(state: GameState): void {
  for (const id of NODE_IDS) {
    const floor = noiseFloor(state.depth, id);
    state.ship.noise[id] = Math.max(floor, (state.ship.noise[id] ?? 0) - RULES.noiseDecay);
  }
  if (state.turn % THREATS.nestNoise.everyTurns === 0) {
    addNoise(state, MAP.nest, depthDef(state.depth).nestNoiseAmount ?? THREATS.nestNoise.amount);
  }
}

export const NEST: NodeId = MAP.nest;
